ci: add CodeFactor
Signed-off-by: xiaoming <2014500726@smail.xtu.edu.cn>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -29,7 +29,7 @@ jobs:
           curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup-init.sh
           chmod +x rustup-init.sh
           ./rustup-init.sh -y
-          rustup install stable  
+          rustup install stable
           rustup target add armv7-unknown-linux-gnueabihf
           rm ./rustup-init.sh
           ln -s /usr/bin/qemu-system-arm /usr/local/bin/qemu-system-arm
@@ -45,17 +45,17 @@ jobs:
       - name: Build all
         run: |
           make
-      
+
       - name: Upload build asserts
         uses: actions/upload-artifact@v2.2.4
         with:
           name: v2p_ca9.elf
           path: |
             ./build/v2p_ca9.elf
-      
+
       - name: Run tests
         run: |
           export QEMU_AUDIO_DRV=none
           timeout --foreground -s SIGKILL 2m make qemu > >(tee run_qemu.log) || {
-            if cat run_qemu.log | grep "Welcome debugging vexpress_v2p_ca9_project" ; then echo "Pass simulation" && exit 0; else echo "Failed in init process" && exit 1; fi; 
+            if cat run_qemu.log | grep "Welcome debugging vexpress_v2p_ca9_project" ; then echo "Pass simulation" && exit 0; else echo "Failed in init process" && exit 1; fi;
           }
